project:
  type: book

# This defines the .qmd files that are in your document
book:
  title: "Calibration Targets for Cache Valley, Utah"
  author:
    - name: Gregory S. Macfarlane
      orcid: 0000-0003-3999-7584
      email: gregmacfarlane@gmail.com
      affiliations:
        - name: Civil and Construction Engineering Department, Brigham Young University
          address: 430 EB
          city: Provo
          state: UT
          postal-code: 84602
    # to add additional authors, simply add another -name: tag 
  date: "1/25/2023"
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_litreview.qmd
    - 03_methods.qmd
    - 04_results.qmd
    - 05_conclusion.qmd
    - references.qmd
  abstract: |
    This report describes calibration targets for travel models derived from both
    a reference trip-based model and an ActivitySim implementation in Cache Valley,
    Utah. The targets are derived from the 2012 Utah Household Travel Survey.

bibliography: references.bib

format:
  html:
    theme: cosmo

